/**
 * \class CFGRuleParser
 * \file CFGRuleParser.h
 *
 * \brief Provide a parser for CFG rules.
 *
 * The code for this parser is indirectly generated from the specification of the BNF
 * grammar for CFGs and the resulting parser class Skeleton.C generated by BNFC.
 *
 * \author Damir Cavar &lt;damir.cavar@gmail.com&gt;
 *
 * \version 0.1
 *
 * \date 2016/10/25 01:53:00
 *
 * \date Created on: Tue Oct 25 01:55:00 2016
 *
 * \copyright Copyright 2016 by Damir Cavar
 *
 * \license{Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.}
 *
 * \see CFGParserTest
 *
 * \note This code should be considered alpha.
 *
 * \bug None
 */


#ifndef GRAMMARTEST_CFGRULEPARSER_H
#define GRAMMARTEST_CFGRULEPARSER_H

#include <iostream>
#include <vector>
#include <limits.h>
//#include "../FLEWFST.h"
#include "Absyn.H"
#include "Parser.H"


using namespace std;


namespace cfg {

    unsigned const int SYMBOL_TYPE_NONE = 0;
    unsigned const int SYMBOL_TYPE_PLAIN = 1;
    unsigned const int SYMBOL_TYPE_AST = 2;
    unsigned const int SYMBOL_TYPE_PLUS = 3;
    unsigned const int SYMBOL_TYPE_OPT = 4;
    unsigned const int SYMBOL_TYPE_DISJUNCTION = 5;

    //using namespace cfg;
    class CFGRuleParser : public Visitor {
    public:
        void visitGrammar(Grammar *p);

        void visitRule(Rule *p);

        void visitLHS(LHS *p);

        void visitDRHS(DRHS *p);

        void visitRHS(RHS *p);

        void visitBRHS(BRHS *p);

        void visitGram(Gram *p);

        void visitRul(Rul *p);

        void visitERul(ERul *p);

        void visitLhsS(LhsS *p);

        void visitRhsDisjSyms(RhsDisjSyms *p);

        void visitRhsDisjSymsP(RhsDisjSymsP *p);

        void visitRhsDisjSymsA(RhsDisjSymsA *p);

        void visitRhsDisjTerminal(RhsDisjTerminal *p);

        void visitRhsDisj(RhsDisj *p);

        void visitRhsBrhsS(RhsBrhsS *p);

        void visitRhsBrhsSP(RhsBrhsSP *p);

        void visitRhsBrhsSA(RhsBrhsSA *p);

        void visitRhsBrhsTerminal(RhsBrhsTerminal *p);

        void visitRhsSymbol(RhsSymbol *p);

        void visitRhsSymbolP(RhsSymbolP *p);

        void visitRhsSymbolA(RhsSymbolA *p);

        void visitRhsTerminal(RhsTerminal *p);

        void visitRhsEpsilon(RhsEpsilon *p);

        void visitRhsBr(RhsBr *p);

        void visitRhsBrPlus(RhsBrPlus *p);

        void visitRhsBrAst(RhsBrAst *p);

        void visitListRule(ListRule *p);

        void visitListRHS(ListRHS *p);

        void visitListBRHS(ListBRHS *p);

        void visitListDRHS(ListDRHS *p);

        void visitInteger(Integer x);

        void visitChar(Char x);

        void visitDouble(Double x);

        void visitString(String x);

        void visitIdent(Ident x);

        // void getRules(const char *str, FLEWFST &newFST);
        void getRules(const char *str);

        bool verbose;

        unsigned long count_rules = 0;

    private:
        // FLEWFST *myFST;
        /*!< the WFST for the grammar */

        unsigned long myLHS;
        /*!< ID of the left-hand-side symbol */

        vector<pair<unsigned long, unsigned int>> myRHS;
        /*!< vector of the right-hand-side symbol IDs and type */

        unsigned long lastState = 0; /*!< ID of the last state in myFST */

        bool optionalSymbol = false;

        bool plusBrSymbol = false;

        bool astBrSymbol = false;

        bool disjunctSymbol = false;

    };
}

#endif //GRAMMARTEST_CFGRULEPARSER_H
