/**
 * \class CFGRuleParser
 * \file CFGRuleParser.cpp
 *
 * \brief Provide a parser for CFG rules.
 *
 * The code for this parser is indirectly generated from the specification of the BNF
 * grammar for CFGs and the resulting parser class Skeleton.C generated by BNFC.
 *
 * \author Damir Cavar &lt;damir.cavar@gmail.com&gt;
 *
 * \version 0.1
 *
 * \date 2016/10/25 01:53:00
 *
 * \date Created on: Tue Oct 25 01:55:00 2016
 *
 * \copyright Copyright 2016 by Damir Cavar
 *
 * \license{Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.}
 *
 * \see CFGParserTest
 *
 * \note This code should be considered alpha.
 *
 * \bug None
 */


#include "CFGRuleParser.h"

namespace cfg {
    void CFGRuleParser::visitGrammar(Grammar *t) {} //abstract class
    void CFGRuleParser::visitRule(Rule *t) {} //abstract class
    void CFGRuleParser::visitLHS(LHS *t) {} //abstract class
    void CFGRuleParser::visitDRHS(DRHS *t) {} //abstract class
    void CFGRuleParser::visitRHS(RHS *t) {} //abstract class
    void CFGRuleParser::visitBRHS(BRHS *t) {} //abstract class

    void CFGRuleParser::getRules(const char *str) {
        Grammar *parse_tree = pGrammar(str);
        if (parse_tree) {
            parse_tree->accept(this);
        }
    }

    /*void CFGRuleParser::getRules(const char *str, FLEWFST &newFST) {
        Grammar *parse_tree = pGrammar(str);
        if (parse_tree) {
            parse_tree->accept(this);
        }
    }*/

    void CFGRuleParser::visitGram(Gram *gram) {
        /* Code For Gram Goes Here */

        gram->listrule_->accept(this);

    }

    void CFGRuleParser::visitRul(Rul *rul) {
        /* Code For Rul Goes Here */

        rul->lhs_->accept(this);
        rul->listrhs_->accept(this);

    }

    void CFGRuleParser::visitERul(ERul *erul) {
        /* Code For ERul Goes Here */


    }

    void CFGRuleParser::visitLhsS(LhsS *lhss) {
        /* Code For LhsS Goes Here */

        visitIdent(lhss->ident_);

    }

    void CFGRuleParser::visitRhsDisjSyms(RhsDisjSyms *rhsdisjsyms) {
        /* Code For RhsDisjSyms Goes Here */

        visitIdent(rhsdisjsyms->ident_);

    }

    void CFGRuleParser::visitRhsDisjSymsP(RhsDisjSymsP *rhsdisjsymsp) {
        /* Code For RhsDisjSymsP Goes Here */

        visitIdent(rhsdisjsymsp->ident_);

    }

    void CFGRuleParser::visitRhsDisjSymsA(RhsDisjSymsA *rhsdisjsymsa) {
        /* Code For RhsDisjSymsA Goes Here */

        visitIdent(rhsdisjsymsa->ident_);

    }

    void CFGRuleParser::visitRhsDisjTerminal(RhsDisjTerminal *rhsdisjterminal) {
        /* Code For RhsDisjTerminal Goes Here */

        visitString(rhsdisjterminal->string_);

    }

    void CFGRuleParser::visitRhsDisj(RhsDisj *rhsdisj) {
        /* Code For RhsDisj Goes Here */

        rhsdisj->listdrhs_->accept(this);

    }

    void CFGRuleParser::visitRhsSymbol(RhsSymbol *rhssymbol) {
        /* Code For RhsSymbol Goes Here */

        visitIdent(rhssymbol->ident_);

    }

    void CFGRuleParser::visitRhsSymbolP(RhsSymbolP *rhssymbolp) {
        /* Code For RhsSymbolP Goes Here */

        visitIdent(rhssymbolp->ident_);

    }

    void CFGRuleParser::visitRhsSymbolA(RhsSymbolA *rhssymbola) {
        /* Code For RhsSymbolA Goes Here */

        visitIdent(rhssymbola->ident_);

    }

    void CFGRuleParser::visitRhsTerminal(RhsTerminal *rhsterminal) {
        /* Code For RhsTerminal Goes Here */

        visitString(rhsterminal->string_);

    }

    void CFGRuleParser::visitRhsEpsilon(RhsEpsilon *rhsepsilon) {
        /* Code For RhsEpsilon Goes Here */


    }

    void CFGRuleParser::visitRhsBr(RhsBr *rhsbr) {
        /* Code For RhsBr Goes Here */

        rhsbr->listbrhs_->accept(this);

    }

    void CFGRuleParser::visitRhsBrPlus(RhsBrPlus *rhsbrplus) {
        /* Code For RhsBrPlus Goes Here */

        rhsbrplus->listbrhs_->accept(this);

    }

    void CFGRuleParser::visitRhsBrAst(RhsBrAst *rhsbrast) {
        /* Code For RhsBrAst Goes Here */

        rhsbrast->listbrhs_->accept(this);

    }

    void CFGRuleParser::visitRhsBrhsS(RhsBrhsS *rhsbrhss) {
        /* Code For RhsBrhsS Goes Here */

        visitIdent(rhsbrhss->ident_);

    }

    void CFGRuleParser::visitRhsBrhsSP(RhsBrhsSP *rhsbrhssp) {
        /* Code For RhsBrhsSP Goes Here */

        visitIdent(rhsbrhssp->ident_);

    }

    void CFGRuleParser::visitRhsBrhsSA(RhsBrhsSA *rhsbrhssa) {
        /* Code For RhsBrhsSA Goes Here */

        visitIdent(rhsbrhssa->ident_);

    }

    void CFGRuleParser::visitRhsBrhsTerminal(RhsBrhsTerminal *rhsbrhsterminal) {
        /* Code For RhsBrhsTerminal Goes Here */

        visitString(rhsbrhsterminal->string_);

    }


    void CFGRuleParser::visitListRule(ListRule *listrule) {
        for (ListRule::iterator i = listrule->begin(); i != listrule->end(); ++i) {
            (*i)->accept(this);
        }
    }

    void CFGRuleParser::visitListRHS(ListRHS *listrhs) {
        for (ListRHS::iterator i = listrhs->begin(); i != listrhs->end(); ++i) {
            (*i)->accept(this);
        }
    }

    void CFGRuleParser::visitListBRHS(ListBRHS *listbrhs) {
        for (ListBRHS::iterator i = listbrhs->begin(); i != listbrhs->end(); ++i) {
            (*i)->accept(this);
        }
    }

    void CFGRuleParser::visitListDRHS(ListDRHS *listdrhs) {
        for (ListDRHS::iterator i = listdrhs->begin(); i != listdrhs->end(); ++i) {
            (*i)->accept(this);
        }
    }


    void CFGRuleParser::visitInteger(Integer x) {
        /* Code for Integer Goes Here */
    }

    void CFGRuleParser::visitChar(Char x) {
        /* Code for Char Goes Here */
    }

    void CFGRuleParser::visitDouble(Double x) {
        /* Code for Double Goes Here */
    }

    void CFGRuleParser::visitString(String x) {
        /* Code for String Goes Here */
    }

    void CFGRuleParser::visitIdent(Ident x) {
        /* Code for Ident Goes Here */
    }

}
