/**
 * \file PCFGParserTest.cpp
 *
 * \brief Provide a parser for PCFG files based on PCFGRuleParser.cpp
 *
 * The purpose of this parser is to test the implementation of the BNF
 * grammar for PCFGs and the resulting parser class generated by BNFC.
 *
 * \author Damir Cavar &lt;damir.cavar@gmail.com&gt;
 *
 * \version 0.2
 *
 * \date 2017/03/26 15:04:00
 *
 * \date Created on: Tue Oct 25 01:55:00 2016
 *
 * \copyright Copyright 2016-2017 by Damir Cavar
 *
 * \license{Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.}
 *
 * \see PCFGRuleParser
 *
 * \note This code should be considered final.
 *
 * \bug None
 */


#include <fstream>
#include <string>
#include <stdio.h>
#include "PCFGRuleParser.h"
#include "../FLEWFST.h"
#include "../SymbolMapper.h"


using namespace pcfg;
using namespace std;

int main(int argc, char **argv) {

    if (argc > 1) {
        std::ifstream ifs(argv[1]);
        std::string content((std::istreambuf_iterator<char>(ifs)),
                            (std::istreambuf_iterator<char>()));

        SymbolMapper *myInputLabels = new SymbolMapper();
        FLEWFST *myWfst = new FLEWFST(myInputLabels);
        myWfst->verbose = false;

        PCFGRuleParser *p = new PCFGRuleParser(myWfst);

        // set the verbose level of the grammar parser
        p->verbose = false;

        p->getRules(content.c_str());
        // cout << endl << "Parsed " << p.countRules << " rules." << endl;
        cout << myWfst->getDOT() << endl;

        delete p;
        delete myWfst;
        delete myInputLabels;
    }
    return 1;
}
